#' Create a landing page
#'
#' Define a function to create a landing page in which users can specify or upload \link{SummarizedExperiment} objects.
#'
#' @param uiFUN Function that accepts a single \code{id} argument and returns a UI element for specifying the SummarizedExperiment.
#' @param seFUN Function that accepts the input value of the UI element generated by \code{uiFUN}
#' and returns a \linkS4class{SummarizedExperiment} object.
#'
#' @return A function that generates a landing page upon being passed to \code{\link{iSEE}}
#' as the \code{landingPage} argument.
#'
#' @details
#' By default, this function creates a landing page in which users can upload an RDS file containing a SummarizedExperiment,
#' which is subsequently read by \code{\link{readRDS}} to launch an instance of \code{\link{iSEE}}.
#' However, any source of SummarizedExperiment objects can be used;
#' for example, we can create UI elements that trigger database queries via \code{seFUN} to create the required object.
#' The parameter name is \code{initialize_INTERNAL_se} and can be used in Shiny bookmarks to initialize the app from a link.
#' 
#' We also provide the \code{initialize_INTERNAL_encoded} input parameter to control the initial state.
#' This should be a base64-encoded string that contains a serialized list of \linkS4class{Panel} objects,
#' which is decoded and unserialized to replace \code{initial} in \code{\link{iSEE}}.
#' Note that only \link{Panel}s classes that were in the original \code{\link{iSEE}} call
#' (as \code{initial} or \code{extra}) will be used for security and other reasons.
#'
#' @section Defining a custom landing page:
#' We note that \code{createLandingPage} is just a limited wrapper around the landing page API.
#' In \code{\link{iSEE}}, \code{landingPage} can be any function with the following argument signature:
#' \itemize{
#' \item \code{FUN}, a function to initialize the \code{\link{iSEE}} observer architecture.
#' This function expects to be passed \code{SE}, a SummarizedExperiment object;
#' and \code{INITIAL}, a list of \linkS4class{Panel} objects describing the initial application state.
#' If \code{INITIAL=NULL}, the initial state from \code{initial} is used instead.
#' \item \code{input}, the Shiny input list.
#' \item \code{output}, the Shiny output list.
#' \item \code{session}, the Shiny session object.
#' }
#'
#' The function should render UI elements into \code{output$allPanels}
#' containing the required widgets to allow a user to set up an \code{\link{iSEE}} session interactively.
#' It should also define observers to respond to those elements and call \code{FUN} with appropriate arguments.
#' All elements should have IDs prefixed with \code{"initialize_INTERNAL"} to avoid conflicts with other elements.
#'
#' @author Aaron Lun
#' @examples
#' createLandingPage()
#'
#' # Alternative approach:
#'
#' @export
#' @importFrom shiny showNotification fileInput HTML observeEvent textInput
#' @importFrom shinyjs hidden
createLandingPage <- function(uiFUN=NULL, seFUN=NULL) {
    if (is.null(uiFUN)) {
        uiFUN <- function(id) fileInput(id, "Choose an RDS file:", multiple = FALSE)
    }
    if (is.null(seFUN)) {
        seFUN <- function(x) readRDS(x$datapath)
    }

    function (FUN, input, output, session) {
        output$allPanels <- renderUI({
            tagList(
               uiFUN("initialize_INTERNAL_se"),
               textInput("initialize_INTERNAL_encoded", "Initial state (base64-encoded):")
            )
        })

        observeEvent(input$initialize_INTERNAL_se, {
            se2 <- try(seFUN(input$initialize_INTERNAL_se), silent=TRUE)
            if (is(se2, "try-error")) {
                showNotification("must upload a valid RDS file", type="error")
            } else if (!is(se2, "SummarizedExperiment")) {
                showNotification("must upload a SummarizedExperiment object", type="error")
            } else {
                init <- try({
                    out <- base64enc::base64decode(input$initialize_INTERNAL_encoded)
                    unserialize(out)
                }, silent=TRUE)
                if (is(init, "try-error")) {
                    init <- NULL
                }
                FUN(SE=se2, INITIAL=init)
            }
        }, ignoreNULL=TRUE, once=TRUE)
    }
}
